version: '2'
services:

# apache based images

  # A base image for apache - based moodle builds
  moodle_apache_base:
      build:
        context: .
        dockerfile: dockerfiles/apache/Dockerfile_base
      image: ellakcy/moodle:apache_base

  # Mysql running variant
  moodle_mysql_db:
    image: mysql
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_ONETIME_PASSWORD: "yes"
      MYSQL_DATABASE: "${MOODLE_DB_NAME}"
      MYSQL_USER: '${MOODLE_MYSQL_USER}'
      MYSQL_PASSWORD: '${MOODLE_MYSQL_PASSWORD}'

  moodle_mysql:
    build:
      context: .
      dockerfile: dockerfiles/apache/Dockerfile_mysql
    image: ellakcy/moodle:mysql_maria_apache
    links:
      - "moodle_mysql_db:moodle_db"
      - "moodle_apache_base"
    ports:
      - "6080:80"
    environment:
      MOODLE_DB_HOST: "moodle_mysql_db"
      MOODLE_DB_NAME: "${MOODLE_DB_NAME}"
      MOODLE_DB_USER: '${MOODLE_MYSQL_USER}'
      MOODLE_DB_PASSWORD: "${MOODLE_MYSQL_PASSWORD}"
      MOODLE_ADMIN: "${MOODLE_ADMIN}"
      MOODLE_ADMIN_PASSWORD: "${MOODLE_ADMIN_PASSWORD}"
      MOODLE_URL: "http://0.0.0.0:6080"

  # postgresql running variant
  moodle_psql_db:
    image: postgres
    environment:
      POSTGRES_DB: "${MOODLE_DB_NAME}"
      POSTGRES_USER: '${MOODLE_MYSQL_USER}'
      POSTGRES_PASSWORD: '${MOODLE_MYSQL_PASSWORD}'

  moodle_psql:
    build:
      context: .
      dockerfile: dockerfiles/apache/Dockerfile_postgrtesql
    image: ellakcy/moodle:postgresql_apache
    links:
      - "moodle_psql_db:moodle_db"
      - "moodle_apache_base"
    ports:
      - "6082:80"
    environment:
      MOODLE_DB_HOST: "moodle_psql_db"
      MOODLE_DB_NAME: "${MOODLE_DB_NAME}"
      MOODLE_DB_USER: '${MOODLE_MYSQL_USER}'
      MOODLE_DB_PASSWORD: "${MOODLE_MYSQL_PASSWORD}"
      MOODLE_ADMIN: "${MOODLE_ADMIN}"
      MOODLE_ADMIN_PASSWORD: "${MOODLE_ADMIN_PASSWORD}"
      MOODLE_URL: "http://0.0.0.0:6082"

  # Testing mariadb support
  moodle_maria_db:
      image: mariadb
      environment:
        MYSQL_RANDOM_ROOT_PASSWORD: "yes"
        MYSQL_ONETIME_PASSWORD: "yes"
        MYSQL_DATABASE: "${MOODLE_DB_NAME}"
        MYSQL_USER: '${MOODLE_MYSQL_USER}'
        MYSQL_PASSWORD: '${MOODLE_MYSQL_PASSWORD}'

  moodle_maria:
      image: ellakcy/moodle:mysql_maria_apache
      links:
        - "moodle_mysql"
        - "moodle_maria_db:moodle_db"
      ports:
        - "6081:80"
      environment:
        MOODLE_DB_HOST: "moodle_maria_db"
        MOODLE_DB_NAME: "${MOODLE_DB_NAME}"
        MOODLE_DB_USER: '${MOODLE_MYSQL_USER}'
        MOODLE_DB_PASSWORD: "${MOODLE_MYSQL_PASSWORD}"
        MOODLE_ADMIN: "${MOODLE_ADMIN}"
        MOODLE_ADMIN_PASSWORD: "${MOODLE_ADMIN_PASSWORD}"
        MOODLE_URL: "http://0.0.0.0:6081"

#Alpine fpm based images



  #Basic alpine fpm image
  moodle_alpine_fpm_base:
    build:
      context: .
      dockerfile: dockerfiles/fpm_alpine/Dockerfile_base
    image: ellakcy/moodle:alpine_fpm_base

  moodle_mysql_alpine_db:
    image: mysql
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_ONETIME_PASSWORD: "yes"
      MYSQL_DATABASE: "${MOODLE_DB_NAME}"
      MYSQL_USER: '${MOODLE_MYSQL_USER}'
      MYSQL_PASSWORD: '${MOODLE_MYSQL_PASSWORD}'

  # Mysql Enabled image

  nginx:
   image: nginx:alpine
   ports:
     - "7070:80"
   volumes:
     - './conf/nginx/nginx.conf:/etc/nginx/nginx.conf:ro'
   links:
     - 'moodle_alpine_fpm_mysql'
   volumes_from:
     - 'moodle_alpine_fpm_mysql'

  moodle_alpine_fpm_mysql:
    build:
      context: .
      dockerfile: dockerfiles/fpm_alpine/Dockerfile_mysql
    image: ellakcy/moodle:mysql_maria_fpm_alpine
    links:
      - "moodle_mysql_alpine_db:moodle_db"
      - "moodle_alpine_fpm_base"
    environment:
      MOODLE_DB_HOST: "moodle_mysql_alpine_db"
      MOODLE_DB_NAME: "${MOODLE_DB_NAME}"
      MOODLE_DB_USER: '${MOODLE_MYSQL_USER}'
      MOODLE_DB_PASSWORD: "${MOODLE_MYSQL_PASSWORD}"
      MOODLE_ADMIN: "${MOODLE_ADMIN}"
      MOODLE_ADMIN_PASSWORD: "${MOODLE_ADMIN_PASSWORD}"
      MOODLE_URL: "http://0.0.0.0:7070"
